# Numpy (Numerical Python)

Numpy, python programlama dili üzerinde çok boyutlu dizi ve matrisler ile çalışmanızı kolaylaştıran bir kütüphanedir. Array'ler ve çok boyutlu matrisler üzerinde yüksek performanslı çalışma imkanı sağlar.

### Neden Numpy?

Basit bir örnekle açıklayalım. İki python array oluşturalım ve bunları çarpalım. Ardından numpy ile çarpalım.

In [2]:
a = [1,2,3,4]
b = [5,6,7,8]

In [3]:
ab = []

for i in range(0, len(a)):
    ab.append(a[i]*b[i])

ab

[5, 12, 21, 32]

Yukarıda a ve b olmak üzere 2 array oluşturduk ve bunların çarpımı için for döngüsü içerisinde çarpım işlemini gerçekleştirip her bir çarpım sonucunu ab array'ine ekledik. Şimdi de bu işlemi numpy kullanarak yapalım.

In [1]:
import numpy as np

In [5]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [6]:
a*b

array([ 5, 12, 21, 32])

Numpy ile çarpım işlemi ise bu kadar basit. Numpy'ın bir diğer güzel tarafı ise veri saklama maliyetinin düşük olmasıdır. Detaylı bilgi için [buraya](https://numpy.org/devdocs/user/basics.html)

### Numpy Array'i oluşturalım

In [7]:
import numpy as np

In [8]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

> Oluşturduğumuz array'in tipi ise numpy altında __ndarray__ nesnesidir.

In [9]:
a = np.array([1,2,3,4,5,6])
type(a)

numpy.ndarray

> Numpy array içerisinde sabit tip kullanmamızı zorunlu tutar.

In [10]:
np.array([3.14,4,2,13])

array([ 3.14,  4.  ,  2.  , 13.  ])

Yukarıda görüldüğü üzere numpy, array içerisinde 1 adet ondalıklı sayı olduğu için diğer tüm int değerleri ondalıklı sayı tipine çevirdi.

> Ancak verinin tipini biz de belirtebiliriz. Integer'a çevirelim.

In [14]:
np.array([3.14,4,2,13], dtype="int")

array([ 3,  4,  2, 13])

#### Sıfırdan Array Oluşturma

Sıfırlardan oluşan bir matris oluşturur.  

> Aşağıda görüldüğü üzere np.zeros 10 elemanlı bir array oluşturdu. Ön tanımlı olarak array'in her bir elemanı ondalıklı sayı olarak düzenlendi.

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

> Elemanların tipini biz de belirleyebiliriz.

In [17]:
np.zeros(10, dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Birlerden Array Oluşturma

3 satır 5 sütunluk 1'lerden oluşan bir matris oluşturalım.

In [18]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

> Elemanların tipini integer olarak değiştirelim

In [19]:
np.ones((3,5), dtype= int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

#### Herhangi bir Sayıdan Matris Oluşturma

Başlıktan da anlaşılacağı üzere 1 ve 0 dışıda herhangi bir sayıda matris oluşturulması gerektiği durumda aşağıdaki gibi oluşturabilirsiniz.

In [21]:
np.full((3,5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

Her bir elemanı "3" sayısından oluşan 3*5'lik 2 boyutlu bir matris oluşturduk. Burada da dtype parametresini kullanarak veri tipini değiştirebilirsiniz.

#### Doğrusal Dizi Oluşturma

Şayet 0'dan 20'ye kadar ikişer ikişer artacak şekilde doğrusal bir array oluşturmak istersek;

In [26]:
np.arange(0,20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

#### İki Sayı Arasında Belirtilen Sayı Kadar Elemanlı Dizi oluşturma

Örneğin 0 ile 1 arasında 10 adet sayı üretilmesini istersek;

In [28]:
np.linspace(0,1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#### Standart Sapma ve Ortalama Değer Bilgisi ile Matris Oluşturma

Verilen belirli bir standart sapma ve belirli bir ortalama değere göre array oluşturma işlemidir.

[Ortalama](https://medium.com/yapayzekaturkiye/merkezi-e%C4%9Filim-%C3%B6l%C3%A7%C3%BCleri-8309dd722b8)sı 10 ve [standart sapması](https://medium.com/yapayzekaturkiye/da%C4%9F%C4%B1l%C4%B1m-%C3%B6l%C3%A7%C3%BCleri-range-159180b395b8)nı 3 verecek şekilde 3*4'lük bir matris tanımlayalım.

In [32]:
np.random.normal(10,3, (3,4))

array([[13.32337277, 11.59815032, 12.31141414,  5.80838844],
       [ 8.49136053, 12.16349058,  8.24307835,  2.49426631],
       [ 5.34056938,  9.62116336, 11.107926  ,  7.54439221]])

Standart sapma ve ortalama değer ile ilgilenmiyor sadece random integer sayı üretmek istiyorsanız aşağıdaki fonksiyonu kullanabilirsiniz.

In [35]:
np.random.randint(0,10,(4,4))

array([[7, 5, 9, 0],
       [7, 1, 9, 9],
       [1, 9, 6, 7],
       [2, 6, 8, 0]])

### Numpy Özellikleri

- **ndim**: boyut sayısı
- **shape**: boyut bilgisi
- **size**: eleman sayısı
- **dtype**: array veri tipi

**0'dan 10'a kadar olacak şekilde 5 elemanlı bir array oluşturalım:**

In [39]:
a = np.random.randint(10, size=5);a

array([8, 6, 2, 8, 1])

**Array'in boyutuna bakalım:**

In [40]:
a.ndim

1

**Boyut bilgisi:** (1 boyutlu array'de 5 eleman var)

In [43]:
a.shape

(5,)

**Size bilgisi:** Toplam eleman Sayısını verir

In [44]:
a.size

5

**Veri Tipi**

In [47]:
a.dtype

dtype('int32')

Yukarıdaki örneği tek boyutlu array için yaptık. Konuyu pekiştirmek için aynı gözlemi 2 boyutlu bir array için de yapalım.

In [49]:
b = np.random.randint(10, size=(3,2));b

array([[9, 4],
       [0, 8],
       [7, 9]])

In [50]:
b.ndim

2

In [51]:
b.shape

(3, 2)

In [53]:
b.size

6

In [54]:
b.dtype

dtype('int32')

### Reshaping (Yeniden Şekillendirme)

Aşağıdaki gibi doğrusal bir array üzerinden nxn'lik bir matris oluşturmak istenildiği veya nxn'lik bir matristen doğrusal bir array oluşturulmak istenildiği durumlarda reshape method'u kullanılır.

**Array'imizi oluşturalım**

In [57]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

**Ardından doğrusal array'imizi reshape methodu ile 3*3'lük bir matris haline getirelim**

In [59]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Aşağıda a isminde bir array oluşturalım daha sonra bu array'i reshape edip b değişkenine atayalım ve sonucu inceleyelim.

In [60]:
a = np.arange(1,10);a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
a.ndim # vektör

1

In [65]:
b = a.reshape((1,9));b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [66]:
b.ndim # reshape sonrası matrisimiz 2 boyutlu hale geldi.

2

Reshape işleminden sonra oluşan array'e dikkatlice bakarsak iki köşeli parantez içinde olduğunu görebiliriz. Bu demek oluyor ki reshape sonrası array'imiz tek boyutlu'dan iki boyutlu, ancak reshape ettiğimiz doğrusal matrisi tek satırda saklayacak şekilde bir matris oluşturmuştur diyebiliriz. 

#### Concantenation (Array Birleştirme İşlemleri)

İki array'i yan yana olacak şekilde birleştirir.

In [68]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [69]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [70]:
z = np.array([7,8,9])

In [71]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

**İki boyutlu array birleştirelim**

In [72]:
a = np.array([[1,2,3],
             [4,5,6]])

In [74]:
np.concatenate([a,a]) # a'yı kendisi ile birleştirelim. default axis=0

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

a matrisini kendisi ile birleştirdiğimizde satır bazında birleştirme işlemi gerçekleşti.

**Sütun bazında birleştirmek istersek axis(eksen) değişkenini kullanmalıyız.**

axis değişkeni ön tanımlı 0 'dır. axis=0 ise satır bazında birleştirme gerçekleşir. axis=1 olarak değiştirirsek sütun bazlı birleştirme gerçekleşir. Aşağıdaki örneği inceleyebilirsiniz.

In [75]:
np.concatenate([a,a], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

#### Splitting (Array Ayırma İşlemleri)

In [85]:
x = np.array([1,2,3,4,5,6,7,8,9,10])

Aşağıdaki örnekte split fonksiyonu indeksi 0.indeksten 3'e kadar, 3'ten 5'e ve 5. indeksten sonraki tüm değerler bir array olacak şekilde diziyi parçalar.

In [82]:
np.split(x, [3,5])

[array([1, 2, 3]), array([4, 5]), array([ 6,  7,  8,  9, 10])]

Buradaki indeks sayısı aşağıdaki gibi artırılabilir.

In [84]:
np.split(x, [2,5,7,9])

[array([1, 2]), array([3, 4, 5]), array([6, 7]), array([8, 9]), array([10])]

**Peki bu parçalamadan elde ettiğimiz array'leri nasıl kullanacağız?**

In [93]:
a,b,c,d,e = np.split(x, [2,5,7,9])

In [94]:
a

array([1, 2])

In [95]:
b

array([3, 4, 5])

In [96]:
c

array([6, 7])

In [97]:
d

array([8, 9])

In [98]:
e

array([10])

Oldukça kolay değil mi? :)

**İki boyutlu matris ayıralım..**

In [91]:
m = np.arange(16).reshape(4,4);m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [92]:
np.vsplit(m, [2]) #m'yi 2. indeks'e kadar böl

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

Böldüğümüz array'i aşağıdaki gibi değişkenlere atayıp kullanabiliriz.

In [99]:
ilk, ikinci = np.vsplit(m, [2]);ilk

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [100]:
ikinci

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

vsplit ile dikey bölümlendirme gerçekleştirdik. Aşağıdaki örnekte ise yatay bölümlendirme işlemini gerçekleştirelim. Örnekleri inceleyerek aradaki farkı kolayca anlayabilirsiniz. 

In [102]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [103]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

#### Sorting (Array Sıralama İşlemleri)

In [107]:
v = np.array([2,6,1,4,5,3]);v

array([2, 6, 1, 4, 5, 3])

In [108]:
np.sort(v)

array([1, 2, 3, 4, 5, 6])

In [109]:
v

array([2, 6, 1, 4, 5, 3])

In [111]:
v.sort();v

array([1, 2, 3, 4, 5, 6])

Burada dikkat edilmesi gereken önemli bir nokta mevcut. np.array ile sort ettiğimizde v array'indeki elemanların indeksleri değişmemesine rağmen v.sort ile **v** array'in sıralaması değişti. yani **v** değişkenine yeni bir atama oldu ve ilk dizilimi kaybettik. Verinin orjinal halinin korunması gereken durumlarda dikkat edilmelidir. 

**İki boyutlu array'lerde Sorting** 

Ortalaması 20, standart sapması 5 olan 3*3'lük bir matris oluşturalım.

In [119]:
m = np.random.normal(20,5,(3,3));m

array([[20.42991592, 16.60338145, 18.42675867],
       [25.04676407, 15.26131091, 27.34962423],
       [17.63663285, 21.49244389, 20.82003102]])

Her bir satırı kendi içinde küçükten büyüğe doğru sıralama

In [115]:
np.sort(m, axis=1)

array([[14.5071129 , 17.73293307, 18.14592682],
       [13.42515085, 16.27577827, 23.88408142],
       [20.37418793, 30.50574639, 30.85841704]])

Sütunlara göre küçükten büyüğe sıralama

In [116]:
np.sort(m, axis=0)

array([[13.42515085, 17.73293307, 14.5071129 ],
       [18.14592682, 23.88408142, 16.27577827],
       [30.85841704, 30.50574639, 20.37418793]])

#### Index ile Elemana Erişmek

In [120]:
a = np.random.randint(10, size=10);a

array([6, 8, 6, 0, 3, 7, 9, 4, 1, 8])

0.index yani dizinin ilk elemanına erişelim

In [121]:
a[0]

6

Listenin en sonundaki elemana erişelim

In [122]:
a[-1]

8

ilk elemanı 55 yapalım

In [123]:
a[0]=55;a

array([55,  8,  6,  0,  3,  7,  9,  4,  1,  8])

**iki boyutta inceleyelim**

In [126]:
m = np.random.randint(10, size=(3,5));m

array([[6, 3, 1, 5, 0],
       [4, 5, 6, 0, 6],
       [4, 5, 2, 4, 3]])

1.satırın 1. elemanına erişim

In [127]:
m[0,0]

6

2.satırın 2. elemanına erişim

In [131]:
m[2,2]

2

In [133]:
m[2,4]

3

In [134]:
m[2,4] = 333;m

array([[  6,   3,   1,   5,   0],
       [  4,   5,   6,   0,   6],
       [  4,   5,   2,   4, 333]])

0.satırın 2. elemanını ondalıklı sayı yapmayı deneyelim.

In [136]:
m

array([[  6,   3,   1,   5,   0],
       [  4,   5,   6,   0,   6],
       [  4,   5,   2,   4, 333]])

In [135]:
m[0,2]

1

In [137]:
m[0,2]=7.7;m

array([[  6,   3,   7,   5,   0],
       [  4,   5,   6,   0,   6],
       [  4,   5,   2,   4, 333]])

Görüldüğü üzere 7.7'yi 7 olarak ekledi. Var olan bir array'e --bu örnekte array'imiz integer değerlere sahip-- dışarıdan farklı bir değer eklenecekse array'in tipi ne ise eklenecek değeri o tipe dönüştürür ve ondan sonra istenen indeks'e ekler. Ancak sıfırdan bir matris oluşturuyor olsaydık tüm değerler integer tek bir değer ondalık sayı olsaydı numpy otomatik olarak tüm değerleri ondalık sayıya dönüştürecekti. Bunun sebebini [buradan](https://www.machinelearningplus.com/python/numpy-tutorial-part1-array-python-examples) okuyabilirsiniz.

#### Slicing (Array Alt Küme İşlemleri)

In [2]:
a = np.arange(20,30);a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

0.indeksten 3.indeks'e kadar olan (3. indeks dahil değil) kısmı getir

In [3]:
a[0:3]

array([20, 21, 22])

In [4]:
a[:3]

array([20, 21, 22])

3.indeksten son elemana kadar git

In [5]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

0.indeksten itibaren ikişer ikişer --eleman atlayarak-- getir

In [6]:
a[0::2]

array([20, 22, 24, 26, 28])

1.indeksten itibaren ikişer ikişer --eleman atlayarak-- getir

In [7]:
a[1::2]

array([21, 23, 25, 27, 29])

0.indeksten itibaren üçer üçer --eleman atlayarak-- getir

In [8]:
a[0::3]

array([20, 23, 26, 29])

**İki boyutlu Slice işlemleri**

In [10]:
m = np.random.randint(10, size=(5,5));m

array([[2, 0, 5, 8, 4],
       [2, 0, 7, 8, 6],
       [3, 1, 9, 4, 9],
       [2, 7, 1, 5, 6],
       [4, 6, 1, 4, 0]])

1.sütuna erişim

In [11]:
m[:,0]

array([2, 2, 3, 2, 4])

1.sütuna erişim

In [13]:
m[:,1]

array([0, 0, 1, 7, 6])

5.sütuna erişim

In [14]:
m[:,4]

array([4, 6, 9, 6, 0])

0.satırın tüm sütunlarını getir

In [15]:
m[0,:]

array([2, 0, 5, 8, 4])

In [16]:
m[0]

array([2, 0, 5, 8, 4])

1.satırın tüm sütunlarını getir

In [17]:
m[1,:]

array([2, 0, 7, 8, 6])

0'dan 2'ye kadar (2 hariç) satırları, 0'dan 3'e kadar (3 hariç) sütunları al

In [18]:
m[0:2, 0:3]

array([[2, 0, 5],
       [2, 0, 7]])

ilk 2 sütunu al

In [22]:
m[:,0:2]

array([[2, 0],
       [2, 0],
       [3, 1],
       [2, 7],
       [4, 6]])

In [20]:
m[::,0:2]

array([[2, 0],
       [2, 0],
       [3, 1],
       [2, 7],
       [4, 6]])

1'den 3'e kadar olan satırlar ile 0'dan 2'ye kadar olan sütunları getir

In [21]:
m[1:3, 0:2]

array([[2, 0],
       [3, 1]])

#### Alt Küme Üzerinde İşlem Yapmak

Alt kümeler üzerinde işlem yaparken dikkat etmemiz gereken bir nokta mevcut. Çok boyutlu matrislerin alt kümeleri üzerinde çalışırken alt küme üzerinde yaptığımız değişikliklerden ana matrisin etkilenmesini yada etkilenmemesini istediğimiz durumlar olabilir. Bu durumda yapılması gerekenler ile ilgili örnekler aşağıda mevcuttur.

In [23]:
a = np.random.randint(10, size=(5,5));a

array([[4, 7, 3, 8, 3],
       [8, 8, 3, 1, 0],
       [8, 1, 2, 3, 9],
       [0, 4, 1, 7, 3],
       [1, 4, 2, 8, 6]])

Öncelikle bir alt küme çekelim

In [24]:
alt_a = a[0:3, 0:2];alt_a

array([[4, 7],
       [8, 8],
       [8, 1]])

Daha sonra çektiğimiz alt kümenin değerleri ile oynayalım

In [26]:
alt_a[0,0] = 3333
alt_a[1,1] = 4444
alt_a

array([[3333,    7],
       [   8, 4444],
       [   8,    1]])

Array'in ilk hali olan **a** değişkenine bakalım ve değişimi gözlemleyelim.

In [27]:
a

array([[3333,    7,    3,    8,    3],
       [   8, 4444,    3,    1,    0],
       [   8,    1,    2,    3,    9],
       [   0,    4,    1,    7,    3],
       [   1,    4,    2,    8,    6]])

Görüldüğü üzere alt kümede yaptığımız değişiklik ana kümeye de etki etti. Bu her zaman istenilen bir şey olmadığı için ana kümeyi etkilemeden de nasıl alt küme üzerinde çalışabiliriz ona bakalım.

In [28]:
b = np.random.randint(10, size=(5,5));b

array([[5, 3, 2, 8, 0],
       [9, 1, 6, 8, 7],
       [6, 7, 2, 4, 3],
       [2, 3, 7, 6, 3],
       [0, 3, 9, 9, 2]])

In [29]:
alt_b = b[0:3, 0:2].copy();alt_b

array([[5, 3],
       [9, 1],
       [6, 7]])

In [30]:
alt_b[0,0] = 3333
alt_b[1,1] = 4444
alt_b

array([[3333,    3],
       [   9, 4444],
       [   6,    7]])

In [31]:
b

array([[5, 3, 2, 8, 0],
       [9, 1, 6, 8, 7],
       [6, 7, 2, 4, 3],
       [2, 3, 7, 6, 3],
       [0, 3, 9, 9, 2]])

Yukarıda görüldüğü üzere alt küme çekerken copy fonksiyonunu çağırırsak alt küme üzerinde yaptığımız değişiklikler ana kümeyi etkilemedi. Proje geliştirirken aradaki farkı bilmek ve ihtiyaca göre uygulamak önemli.

#### Fancy Index ile Elemanlara Erişmek

Fancy index kavramı önemli. Pandas ve numpy arraylerinde daha ileri düzeyde eleman seçmemize olanak tanır.

In [32]:
x = np.arange(0,30,3);x

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

Elemanlara basit erişim

In [34]:
x[1]

3

In [35]:
x[4]

12

In [36]:
x[6]

18

In [37]:
[x[2], x[4], x[7]]

[6, 12, 21]

Fancy index ile erişim

Index içeren 3 elemanlı bir array oluşturalım ve bu index bilgisini x arrayinden çekelim

In [39]:
alt_indexes = [1,3,7]

In [40]:
x[alt_indexes]

array([ 3,  9, 21])

Görüldüğü üzere 1. 3. ve 7. indexlerin karşılığı olan değerleri çekebildik. Bu index'lere karşılık gelecek değerleri normalde for döngüsü ile alabilirdik ancak fancy index işimizi oldukça kolaylaştırdı.

**2 boyutta Fancy Index**

3'e 3'lük bir matris oluşturalım

In [43]:
z = np.arange(9).reshape((3,3));z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [45]:
z[satir,sutun]

array([1, 5])

Satıların tamamı ile 1. ve 2. sütunları getir

In [46]:
z[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

#### Koşullu Eleman İşlemleri

Belirli bir vektör yada array'in içinde belirli bir koşulu sağlayan değerleri getirmeye yarar.

In [47]:
v = np.array([1,2,3,4,5])

In [48]:
v > 5

array([False, False, False, False, False])

In [49]:
v < 3

array([ True,  True, False, False, False])

3'ten küçük olanları getir

In [50]:
v[v < 3]

array([1, 2])

3'ten büyük yada eşit olanları getir

In [51]:
v[v >= 3]

array([3, 4, 5])

3'ten küçük yada eşit olanları getir

In [52]:
v[v <= 3]

array([1, 2, 3])

3'e eşit olanları getir

In [53]:
v[v == 3]

array([3])

3 olmayanları getir

In [54]:
v[v != 3]

array([1, 2, 4, 5])

Tüm elemanları 2 ile çarpalım

In [55]:
v * 2

array([ 2,  4,  6,  8, 10])

Tüm elemanları 4'e bölelim

In [56]:
v / 4

array([0.25, 0.5 , 0.75, 1.  , 1.25])

5'e çarpıp 10'a bölelim

In [57]:
v * 5 / 10

array([0.5, 1. , 1.5, 2. , 2.5])

Tüm elemanların karesini alalım

In [58]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

#### Matematiksel İşlemler

Yukarıda yaptığımız ve aşağıda yapacağımız matematiksel işlemler arka planda **ufunc** adı verilen bir mekanizma çalışıyor. Yani v * 3 işlemi arka planda numpy tarafından bir dizi işlemden geçip array'in her bir elemanı ile 3 sayısı çarpılıp bize sonucu iletiliyor. Şimdi aşağıdaki örneğe bakalım.

v - 1 işlemini numpy'a farklı yöntemle yaptıralım.

In [62]:
v = np.array([1,2,3,4,5]);v # array'i oluşturduk

array([1, 2, 3, 4, 5])

In [61]:
np.subtract(v, 1) # vektörden 1 çıkar

array([0, 1, 2, 3, 4])

Buradan anlamamız gereken matematiksel operatörler (+, -, *, /, ...) ile yapabildiğimiz işlemleri istersen ufunc ile de yapabiliyoruz. Biraz daha örnek vermek gerekirse;

In [63]:
np.add(v, 5)

array([ 6,  7,  8,  9, 10])

In [64]:
np.multiply(v, 3)

array([ 3,  6,  9, 12, 15])

In [66]:
np.divide(v, 2)

array([0.5, 1. , 1.5, 2. , 2.5])

In [67]:
np.power(v, 3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [68]:
v**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [69]:
np.mod(v, 2) # 2 ile bölümden kalan

array([1, 0, 1, 0, 1], dtype=int32)

In [70]:
v % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [71]:
np.absolute(np.array([-3])) # -3'ün mutlak değerini alalım

array([3])

In [74]:
np.sin(60) # sinus 60

-0.3048106211022167

In [75]:
np.cos(60)

-0.9524129804151563

In [76]:
np.log(v) # v'nin tüm elemanlarının logaritması

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [77]:
np.log2(v) # logaritmanın derecesini belirterek alalım

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809])

In [78]:
np.log10(v) # logaritmanın derecesini belirterek alalım

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ])

**Daha fazlası için [buraya](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf) bakabilirsiniz.**

#### İstatistiksel Hesaplamalar

In [83]:
v

array([1, 2, 3, 4, 5])

v array'inin ortalamasına bakalım

In [84]:
np.mean(v)

3.0

toplam değer

In [85]:
v.sum()

15

en küçük eleman

In [86]:
v.min()

1

en büyük eleman

In [87]:
v.max()

5